apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mp-dashboard-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: mp-static-ip
    networking.gke.io/managed-certificates: mp-managed-cert
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    networking.gke.io/v1beta1.FrontendConfig: "mp-dashboard-frontend"
spec:
  defaultBackend:
    service:
      name: mp-server-svc
      port:
        number: 80
