apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: midpoint-beconfig
spec:
  healthCheck:
    checkIntervalSec: 120
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTPS
    requestPath: "/midpoint"
    

