apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: mp-beconfig
spec:
  timeoutSec: 30
  healthCheck:
    checkIntervalSec: 120
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: "/midpoint/actuator/health"
