
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: mp-config
    files:
      - ./config/111_sysconfig-deployment.xml

resources:
  - mp-sts.yaml
  - mp-svc.yaml
